version: '2'

volumes:
  orderer.certverification.com:
  ca.CPA.certverification.com:
  ca.verifier.certverification.com:
  peer0.CPA.certverification.com:
  peer1.CPA.certverification.com:
  peer0.verifier.certverification.com:
  peer1.verifier.certverification.com:

networks:
  cert:

services:

  orderer.certverification.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.certverification.com
    container_name: orderer.certverification.com
    networks:
      - cert

  peer0.CPA.certverification.com:
    container_name: peer0.CPA.certverification.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.CPA.certverification.com
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=peer0.cpacouchdb:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    depends_on:
      - peer0.cpacouchdb
    networks:
      - cert

  peer0.cpacouchdb:
    container_name: peer0.cpacouchdb
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - "5984:5984"
    networks:
      - cert

  peer1.CPA.certverification.com:
    container_name: peer1.CPA.certverification.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.CPA.certverification.com
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=peer1.cpacouchdb:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    depends_on:
      - peer1.cpacouchdb
    networks:
      - cert

  peer1.cpacouchdb:
    container_name: peer1.cpacouchdb
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - "6984:5984"
    networks:
      - cert

  peer0.verifier.certverification.com:
    container_name: peer0.verifier.certverification.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.verifier.certverification.com
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=peer0.verifiercouchdb:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    depends_on:
      - peer0.verifiercouchdb
    networks:
      - cert

  peer0.verifiercouchdb:
    container_name: peer0.verifiercouchdb
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - "7984:5984"
    networks:
      - cert
  
  peer1.verifier.certverification.com:
    container_name: peer1.verifier.certverification.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.verifier.certverification.com
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=peer1.verifiercouchdb:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    depends_on:
      - peer1.verifiercouchdb
    networks:
      - cert

  peer1.verifiercouchdb:
    container_name: peer1.verifiercouchdb
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - "8984:5984"
    networks:
      - cert

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - SYS_CHANNEL=$SYS_CHANNEL
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.CPA.certverification.com:7051
      - CORE_PEER_LOCALMSPID=CPAMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/CPA.certverification.com/peers/peer0.CPA.certverification.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/CPA.certverification.com/peers/peer0.CPA.certverification.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/CPA.certverification.com/peers/peer0.CPA.certverification.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/CPA.certverification.com/users/Admin@CPA.certverification.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.certverification.com
      - ca.CPA.certverification.com
      - ca.verifier.certverification.com
      - peer0.CPA.certverification.com
      - peer1.CPA.certverification.com
      - peer0.verifier.certverification.com
      - peer1.verifier.certverification.com
    networks:
      - cert

  ca.CPA.certverification.com:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-cpa
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.CPA.certverification.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/2fc56fd5b2b3894f1427fa1ab9af7d99838d18a29bdf2a977732794927920096_sk
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.CPA.certverification.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/2fc56fd5b2b3894f1427fa1ab9af7d99838d18a29bdf2a977732794927920096_sk -b admin:adminpw -d'
    volumes:
      - ./fabric-ca-server-config.yaml:/etc/hyperledger/fabric-ca-server/fabric-ca-server-config.yaml
      - ./crypto-config/peerOrganizations/CPA.certverification.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peercpa
    networks:
      - cert

  ca.verifier.certverification.com:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-verifier
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.verifier.certverification.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/92a78a0750b89a8d53ecd00f3dc581de7ff8fddf53e70fb8c756246d635a7321_sk
      - FABRIC_CA_SERVER_PORT=8054
    ports:
      - "8054:8054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.verifier.certverification.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/92a78a0750b89a8d53ecd00f3dc581de7ff8fddf53e70fb8c756246d635a7321_sk -b admin:adminpw -d'
    volumes:
      - ./fabric-ca-server-config.yaml:/etc/hyperledger/fabric-ca-server/fabric-ca-server-config.yaml
      - ./crypto-config/peerOrganizations/verifier.certverification.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerverifier
    networks:
      - cert
