version: '2'

services:

  orderer.certverification.com:
    container_name: orderer.certverification.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/certverification.com/orderers/orderer.certverification.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/certverification.com/orderers/orderer.certverification.com/tls/:/var/hyperledger/orderer/tls
        - orderer.certverification.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.CPA.certverification.com:
    container_name: peer0.CPA.certverification.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.CPA.certverification.com
      - CORE_PEER_ADDRESS=peer0.CPA.certverification.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.CPA.certverification.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.CPA.certverification.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.CPA.certverification.com:7051
      - CORE_PEER_LOCALMSPID=CPAMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/CPA.certverification.com/peers/peer0.CPA.certverification.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/CPA.certverification.com/peers/peer0.CPA.certverification.com/tls:/etc/hyperledger/fabric/tls
        - peer0.CPA.certverification.com:/var/hyperledger/production
    ports:
      - 7051:7051

  peer1.CPA.certverification.com:
    container_name: peer1.CPA.certverification.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.CPA.certverification.com
      - CORE_PEER_ADDRESS=peer1.CPA.certverification.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.CPA.certverification.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.CPA.certverification.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.CPA.certverification.com:8051
      - CORE_PEER_LOCALMSPID=CPAMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/CPA.certverification.com/peers/peer1.CPA.certverification.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/CPA.certverification.com/peers/peer1.CPA.certverification.com/tls:/etc/hyperledger/fabric/tls
        - peer1.CPA.certverification.com:/var/hyperledger/production
    ports:
      - 8051:8051

  peer0.verifier.certverification.com:
    container_name: peer0.verifier.certverification.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.verifier.certverification.com
      - CORE_PEER_ADDRESS=peer0.verifier.certverification.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.verifier.certverification.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.verifier.certverification.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.verifier.certverification.com:10051
      - CORE_PEER_LOCALMSPID=VerifierMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/verifier.certverification.com/peers/peer0.verifier.certverification.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/verifier.certverification.com/peers/peer0.verifier.certverification.com/tls:/etc/hyperledger/fabric/tls
        - peer0.verifier.certverification.com:/var/hyperledger/production
    ports:
      - 9051:9051

  peer1.verifier.certverification.com:
    container_name: peer1.verifier.certverification.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.verifier.certverification.com
      - CORE_PEER_ADDRESS=peer1.verifier.certverification.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer1.verifier.certverification.com:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.verifier.certverification.com:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.verifier.certverification.com:9051
      - CORE_PEER_LOCALMSPID=VerifierMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/verifier.certverification.com/peers/peer1.verifier.certverification.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/verifier.certverification.com/peers/peer1.verifier.certverification.com/tls:/etc/hyperledger/fabric/tls
        - peer1.verifier.certverification.com:/var/hyperledger/production
    ports:
      - 10051:10051
