NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.CPA.certverification.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.CPA.certverification.com-cert.pem
    OrganizationalUnitIdentifier: peer
